apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecosystem-home-api
    tier: api
  name: ecosystem-home-api
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ecosystem-home-api
    tier: api
  sessionAffinity: None
  type: ClusterIP
