apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecosystem-home-api
    tier: api
  name: ecosystem-home-api
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ecosystem-home-api
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ecosystem-home-api
        tier: api
    spec:
      containers:
      - env:
        - name: APP_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: APP_SECRET_KEY
              name: ecosystem-home-api-config
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: ecosystem-home-api-config
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              key: MONGO_USER
              name: ecosystem-home-api-config
        - name: MONGO_PW
          valueFrom:
            configMapKeyRef:
              key: MONGO_PW
              name: ecosystem-home-api-config
        image: registry.gitlab.com/btbtravis/ecosystem-home-api:0.0.1
        imagePullPolicy: IfNotPresent
        name: ecosystem-home-api-api
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ecosystem-home-api-gitlab
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
